/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: 9746e54feb788c0417d8b44ffb27b752)
interface __BaseEnv_Env {
	DB: D1Database;
	MEMORY_VECTORIZE: VectorizeIndex;
	AI: Ai;
	PORT: string;
	WEB_PORT: string;
	TAB_API_BASE_URL: string;
	TAB_WEB_BASE_URL: string;
	TAB_DEVICE_ID: string;
	TAB_DEBUG_TYPING_OVERLAY: string;
	TAB_SHOW_SETTINGS_ON_START: string;
	BETTER_AUTH_URL: string;
	BETTER_AUTH_SECRET: string;
	GROQ_API_KEY: string;
	AI_GATEWAY_API_KEY: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_DATABASE_ID: string;
	CLOUDFLARE_D1_TOKEN: string;
	TAB_MAC_DOWNLOAD_URL: string;
	TAB_DESKTOP_LATEST_VERSION: string;
	POLAR_ACCESS_TOKEN: string;
	POLAR_ORGANIZATION_ID: string;
	POLAR_CHECKOUT_SUCCESS_URL: string;
	POLAR_WEBHOOK_SECRET: string;
	POLAR_SERVER: string;
	POLAR_SEND_ORGANIZATION_ID: string;
	POLAR_DEEP_COMPLETE_METER_ID: string;
	POLAR_CREDITS_BENEFIT_ID_PRO_MONTHLY: string;
	POLAR_PRODUCT_ID_PRO_MONTHLY: string;
	POLAR_CREDITS_BENEFIT_ID_MAX_MONTHLY: string;
	POLAR_PRODUCT_ID_MAX_MONTHLY: string;
	RESEND_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./apps/api/src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PORT" | "WEB_PORT" | "TAB_API_BASE_URL" | "TAB_WEB_BASE_URL" | "TAB_DEVICE_ID" | "TAB_DEBUG_TYPING_OVERLAY" | "TAB_SHOW_SETTINGS_ON_START" | "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET" | "GROQ_API_KEY" | "AI_GATEWAY_API_KEY" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_DATABASE_ID" | "CLOUDFLARE_D1_TOKEN" | "TAB_MAC_DOWNLOAD_URL" | "TAB_DESKTOP_LATEST_VERSION" | "POLAR_ACCESS_TOKEN" | "POLAR_ORGANIZATION_ID" | "POLAR_CHECKOUT_SUCCESS_URL" | "POLAR_WEBHOOK_SECRET" | "POLAR_SERVER" | "POLAR_SEND_ORGANIZATION_ID" | "POLAR_DEEP_COMPLETE_METER_ID" | "POLAR_CREDITS_BENEFIT_ID_PRO_MONTHLY" | "POLAR_PRODUCT_ID_PRO_MONTHLY" | "POLAR_CREDITS_BENEFIT_ID_MAX_MONTHLY" | "POLAR_PRODUCT_ID_MAX_MONTHLY" | "RESEND_API_KEY">> {}
}
