/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3280a62d76e8424901dffa3dec5b49d5)
interface __BaseEnv_Env {
	DB: D1Database;
	MEMORY_VECTORIZE: VectorizeIndex;
	AI: Ai;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./apps/api/src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
