/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingPortalRouteImport } from './routes/billing.portal'
import { Route as BillingCheckoutRouteImport } from './routes/billing.checkout'
import { Route as DownloadTabbDmgRouteImport } from './routes/download.tabb.dmg'
import { Route as DownloadLatestJsonRouteImport } from './routes/download.latest.json'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingPortalRoute = BillingPortalRouteImport.update({
  id: '/billing/portal',
  path: '/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCheckoutRoute = BillingCheckoutRouteImport.update({
  id: '/billing/checkout',
  path: '/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadTabbDmgRoute = DownloadTabbDmgRouteImport.update({
  id: '/tabb/dmg',
  path: '/tabb/dmg',
  getParentRoute: () => DownloadRoute,
} as any)
const DownloadLatestJsonRoute = DownloadLatestJsonRouteImport.update({
  id: '/latest/json',
  path: '/latest/json',
  getParentRoute: () => DownloadRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/portal': typeof BillingPortalRoute
  '/download/latest/json': typeof DownloadLatestJsonRoute
  '/download/tabb/dmg': typeof DownloadTabbDmgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/portal': typeof BillingPortalRoute
  '/download/latest/json': typeof DownloadLatestJsonRoute
  '/download/tabb/dmg': typeof DownloadTabbDmgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/portal': typeof BillingPortalRoute
  '/download/latest/json': typeof DownloadLatestJsonRoute
  '/download/tabb/dmg': typeof DownloadTabbDmgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/download'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/signup'
    | '/billing/checkout'
    | '/billing/portal'
    | '/download/latest/json'
    | '/download/tabb/dmg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/download'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/signup'
    | '/billing/checkout'
    | '/billing/portal'
    | '/download/latest/json'
    | '/download/tabb/dmg'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/download'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/signup'
    | '/billing/checkout'
    | '/billing/portal'
    | '/download/latest/json'
    | '/download/tabb/dmg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  DownloadRoute: typeof DownloadRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  BillingCheckoutRoute: typeof BillingCheckoutRoute
  BillingPortalRoute: typeof BillingPortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/portal': {
      id: '/billing/portal'
      path: '/billing/portal'
      fullPath: '/billing/portal'
      preLoaderRoute: typeof BillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/checkout': {
      id: '/billing/checkout'
      path: '/billing/checkout'
      fullPath: '/billing/checkout'
      preLoaderRoute: typeof BillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/tabb/dmg': {
      id: '/download/tabb/dmg'
      path: '/tabb/dmg'
      fullPath: '/download/tabb/dmg'
      preLoaderRoute: typeof DownloadTabbDmgRouteImport
      parentRoute: typeof DownloadRoute
    }
    '/download/latest/json': {
      id: '/download/latest/json'
      path: '/latest/json'
      fullPath: '/download/latest/json'
      preLoaderRoute: typeof DownloadLatestJsonRouteImport
      parentRoute: typeof DownloadRoute
    }
  }
}

interface DownloadRouteChildren {
  DownloadLatestJsonRoute: typeof DownloadLatestJsonRoute
  DownloadTabbDmgRoute: typeof DownloadTabbDmgRoute
}

const DownloadRouteChildren: DownloadRouteChildren = {
  DownloadLatestJsonRoute: DownloadLatestJsonRoute,
  DownloadTabbDmgRoute: DownloadTabbDmgRoute,
}

const DownloadRouteWithChildren = DownloadRoute._addFileChildren(
  DownloadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  DownloadRoute: DownloadRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  BillingCheckoutRoute: BillingCheckoutRoute,
  BillingPortalRoute: BillingPortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
