/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DownloadTabDotdmgRouteImport } from './routes/download.tab[.]dmg'
import { Route as DownloadLatestDotjsonRouteImport } from './routes/download.latest[.]json'
import { Route as DashboardUsageRouteImport } from './routes/dashboard.usage'
import { Route as DashboardMemoriesRouteImport } from './routes/dashboard.memories'
import { Route as DashboardDevicesRouteImport } from './routes/dashboard.devices'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as BillingPortalRouteImport } from './routes/billing.portal'
import { Route as BillingErrorRouteImport } from './routes/billing.error'
import { Route as BillingCheckoutRouteImport } from './routes/billing.checkout'
import { Route as DashboardMemoriesExportRouteImport } from './routes/dashboard.memories.export'
import { Route as DashboardMemoriesDeleteSelectedRouteImport } from './routes/dashboard.memories.delete-selected'
import { Route as DashboardMemoriesCreateRouteImport } from './routes/dashboard.memories.create'
import { Route as DashboardMemoriesMemoryIdEditRouteImport } from './routes/dashboard.memories.$memoryId.edit'
import { Route as DashboardMemoriesMemoryIdDeleteRouteImport } from './routes/dashboard.memories.$memoryId.delete'
import { Route as DashboardDevicesDeviceIdRevokeRouteImport } from './routes/dashboard.devices.$deviceId.revoke'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DownloadTabDotdmgRoute = DownloadTabDotdmgRouteImport.update({
  id: '/tab.dmg',
  path: '/tab.dmg',
  getParentRoute: () => DownloadRoute,
} as any)
const DownloadLatestDotjsonRoute = DownloadLatestDotjsonRouteImport.update({
  id: '/latest.json',
  path: '/latest.json',
  getParentRoute: () => DownloadRoute,
} as any)
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMemoriesRoute = DashboardMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevicesRoute = DashboardDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const BillingPortalRoute = BillingPortalRouteImport.update({
  id: '/billing/portal',
  path: '/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingErrorRoute = BillingErrorRouteImport.update({
  id: '/billing/error',
  path: '/billing/error',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCheckoutRoute = BillingCheckoutRouteImport.update({
  id: '/billing/checkout',
  path: '/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMemoriesExportRoute = DashboardMemoriesExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => DashboardMemoriesRoute,
} as any)
const DashboardMemoriesDeleteSelectedRoute =
  DashboardMemoriesDeleteSelectedRouteImport.update({
    id: '/delete-selected',
    path: '/delete-selected',
    getParentRoute: () => DashboardMemoriesRoute,
  } as any)
const DashboardMemoriesCreateRoute = DashboardMemoriesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardMemoriesRoute,
} as any)
const DashboardMemoriesMemoryIdEditRoute =
  DashboardMemoriesMemoryIdEditRouteImport.update({
    id: '/$memoryId/edit',
    path: '/$memoryId/edit',
    getParentRoute: () => DashboardMemoriesRoute,
  } as any)
const DashboardMemoriesMemoryIdDeleteRoute =
  DashboardMemoriesMemoryIdDeleteRouteImport.update({
    id: '/$memoryId/delete',
    path: '/$memoryId/delete',
    getParentRoute: () => DashboardMemoriesRoute,
  } as any)
const DashboardDevicesDeviceIdRevokeRoute =
  DashboardDevicesDeviceIdRevokeRouteImport.update({
    id: '/$deviceId/revoke',
    path: '/$deviceId/revoke',
    getParentRoute: () => DashboardDevicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/brand': typeof BrandRoute
  '/components': typeof ComponentsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/error': typeof BillingErrorRoute
  '/billing/portal': typeof BillingPortalRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/devices': typeof DashboardDevicesRouteWithChildren
  '/dashboard/memories': typeof DashboardMemoriesRouteWithChildren
  '/dashboard/usage': typeof DashboardUsageRoute
  '/download/latest.json': typeof DownloadLatestDotjsonRoute
  '/download/tab.dmg': typeof DownloadTabDotdmgRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/memories/create': typeof DashboardMemoriesCreateRoute
  '/dashboard/memories/delete-selected': typeof DashboardMemoriesDeleteSelectedRoute
  '/dashboard/memories/export': typeof DashboardMemoriesExportRoute
  '/dashboard/devices/$deviceId/revoke': typeof DashboardDevicesDeviceIdRevokeRoute
  '/dashboard/memories/$memoryId/delete': typeof DashboardMemoriesMemoryIdDeleteRoute
  '/dashboard/memories/$memoryId/edit': typeof DashboardMemoriesMemoryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/brand': typeof BrandRoute
  '/components': typeof ComponentsRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/error': typeof BillingErrorRoute
  '/billing/portal': typeof BillingPortalRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/devices': typeof DashboardDevicesRouteWithChildren
  '/dashboard/memories': typeof DashboardMemoriesRouteWithChildren
  '/dashboard/usage': typeof DashboardUsageRoute
  '/download/latest.json': typeof DownloadLatestDotjsonRoute
  '/download/tab.dmg': typeof DownloadTabDotdmgRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/memories/create': typeof DashboardMemoriesCreateRoute
  '/dashboard/memories/delete-selected': typeof DashboardMemoriesDeleteSelectedRoute
  '/dashboard/memories/export': typeof DashboardMemoriesExportRoute
  '/dashboard/devices/$deviceId/revoke': typeof DashboardDevicesDeviceIdRevokeRoute
  '/dashboard/memories/$memoryId/delete': typeof DashboardMemoriesMemoryIdDeleteRoute
  '/dashboard/memories/$memoryId/edit': typeof DashboardMemoriesMemoryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/brand': typeof BrandRoute
  '/components': typeof ComponentsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/error': typeof BillingErrorRoute
  '/billing/portal': typeof BillingPortalRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/devices': typeof DashboardDevicesRouteWithChildren
  '/dashboard/memories': typeof DashboardMemoriesRouteWithChildren
  '/dashboard/usage': typeof DashboardUsageRoute
  '/download/latest.json': typeof DownloadLatestDotjsonRoute
  '/download/tab.dmg': typeof DownloadTabDotdmgRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/memories/create': typeof DashboardMemoriesCreateRoute
  '/dashboard/memories/delete-selected': typeof DashboardMemoriesDeleteSelectedRoute
  '/dashboard/memories/export': typeof DashboardMemoriesExportRoute
  '/dashboard/devices/$deviceId/revoke': typeof DashboardDevicesDeviceIdRevokeRoute
  '/dashboard/memories/$memoryId/delete': typeof DashboardMemoriesMemoryIdDeleteRoute
  '/dashboard/memories/$memoryId/edit': typeof DashboardMemoriesMemoryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/brand'
    | '/components'
    | '/contact'
    | '/dashboard'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/billing/checkout'
    | '/billing/error'
    | '/billing/portal'
    | '/dashboard/account'
    | '/dashboard/devices'
    | '/dashboard/memories'
    | '/dashboard/usage'
    | '/download/latest.json'
    | '/download/tab.dmg'
    | '/dashboard/'
    | '/dashboard/memories/create'
    | '/dashboard/memories/delete-selected'
    | '/dashboard/memories/export'
    | '/dashboard/devices/$deviceId/revoke'
    | '/dashboard/memories/$memoryId/delete'
    | '/dashboard/memories/$memoryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/brand'
    | '/components'
    | '/contact'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/billing/checkout'
    | '/billing/error'
    | '/billing/portal'
    | '/dashboard/account'
    | '/dashboard/devices'
    | '/dashboard/memories'
    | '/dashboard/usage'
    | '/download/latest.json'
    | '/download/tab.dmg'
    | '/dashboard'
    | '/dashboard/memories/create'
    | '/dashboard/memories/delete-selected'
    | '/dashboard/memories/export'
    | '/dashboard/devices/$deviceId/revoke'
    | '/dashboard/memories/$memoryId/delete'
    | '/dashboard/memories/$memoryId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/brand'
    | '/components'
    | '/contact'
    | '/dashboard'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/billing/checkout'
    | '/billing/error'
    | '/billing/portal'
    | '/dashboard/account'
    | '/dashboard/devices'
    | '/dashboard/memories'
    | '/dashboard/usage'
    | '/download/latest.json'
    | '/download/tab.dmg'
    | '/dashboard/'
    | '/dashboard/memories/create'
    | '/dashboard/memories/delete-selected'
    | '/dashboard/memories/export'
    | '/dashboard/devices/$deviceId/revoke'
    | '/dashboard/memories/$memoryId/delete'
    | '/dashboard/memories/$memoryId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BrandRoute: typeof BrandRoute
  ComponentsRoute: typeof ComponentsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DownloadRoute: typeof DownloadRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  BillingCheckoutRoute: typeof BillingCheckoutRoute
  BillingErrorRoute: typeof BillingErrorRoute
  BillingPortalRoute: typeof BillingPortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/download/tab.dmg': {
      id: '/download/tab.dmg'
      path: '/tab.dmg'
      fullPath: '/download/tab.dmg'
      preLoaderRoute: typeof DownloadTabDotdmgRouteImport
      parentRoute: typeof DownloadRoute
    }
    '/download/latest.json': {
      id: '/download/latest.json'
      path: '/latest.json'
      fullPath: '/download/latest.json'
      preLoaderRoute: typeof DownloadLatestDotjsonRouteImport
      parentRoute: typeof DownloadRoute
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/memories': {
      id: '/dashboard/memories'
      path: '/memories'
      fullPath: '/dashboard/memories'
      preLoaderRoute: typeof DashboardMemoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/devices': {
      id: '/dashboard/devices'
      path: '/devices'
      fullPath: '/dashboard/devices'
      preLoaderRoute: typeof DashboardDevicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/billing/portal': {
      id: '/billing/portal'
      path: '/billing/portal'
      fullPath: '/billing/portal'
      preLoaderRoute: typeof BillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/error': {
      id: '/billing/error'
      path: '/billing/error'
      fullPath: '/billing/error'
      preLoaderRoute: typeof BillingErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/checkout': {
      id: '/billing/checkout'
      path: '/billing/checkout'
      fullPath: '/billing/checkout'
      preLoaderRoute: typeof BillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/memories/export': {
      id: '/dashboard/memories/export'
      path: '/export'
      fullPath: '/dashboard/memories/export'
      preLoaderRoute: typeof DashboardMemoriesExportRouteImport
      parentRoute: typeof DashboardMemoriesRoute
    }
    '/dashboard/memories/delete-selected': {
      id: '/dashboard/memories/delete-selected'
      path: '/delete-selected'
      fullPath: '/dashboard/memories/delete-selected'
      preLoaderRoute: typeof DashboardMemoriesDeleteSelectedRouteImport
      parentRoute: typeof DashboardMemoriesRoute
    }
    '/dashboard/memories/create': {
      id: '/dashboard/memories/create'
      path: '/create'
      fullPath: '/dashboard/memories/create'
      preLoaderRoute: typeof DashboardMemoriesCreateRouteImport
      parentRoute: typeof DashboardMemoriesRoute
    }
    '/dashboard/memories/$memoryId/edit': {
      id: '/dashboard/memories/$memoryId/edit'
      path: '/$memoryId/edit'
      fullPath: '/dashboard/memories/$memoryId/edit'
      preLoaderRoute: typeof DashboardMemoriesMemoryIdEditRouteImport
      parentRoute: typeof DashboardMemoriesRoute
    }
    '/dashboard/memories/$memoryId/delete': {
      id: '/dashboard/memories/$memoryId/delete'
      path: '/$memoryId/delete'
      fullPath: '/dashboard/memories/$memoryId/delete'
      preLoaderRoute: typeof DashboardMemoriesMemoryIdDeleteRouteImport
      parentRoute: typeof DashboardMemoriesRoute
    }
    '/dashboard/devices/$deviceId/revoke': {
      id: '/dashboard/devices/$deviceId/revoke'
      path: '/$deviceId/revoke'
      fullPath: '/dashboard/devices/$deviceId/revoke'
      preLoaderRoute: typeof DashboardDevicesDeviceIdRevokeRouteImport
      parentRoute: typeof DashboardDevicesRoute
    }
  }
}

interface DashboardDevicesRouteChildren {
  DashboardDevicesDeviceIdRevokeRoute: typeof DashboardDevicesDeviceIdRevokeRoute
}

const DashboardDevicesRouteChildren: DashboardDevicesRouteChildren = {
  DashboardDevicesDeviceIdRevokeRoute: DashboardDevicesDeviceIdRevokeRoute,
}

const DashboardDevicesRouteWithChildren =
  DashboardDevicesRoute._addFileChildren(DashboardDevicesRouteChildren)

interface DashboardMemoriesRouteChildren {
  DashboardMemoriesCreateRoute: typeof DashboardMemoriesCreateRoute
  DashboardMemoriesDeleteSelectedRoute: typeof DashboardMemoriesDeleteSelectedRoute
  DashboardMemoriesExportRoute: typeof DashboardMemoriesExportRoute
  DashboardMemoriesMemoryIdDeleteRoute: typeof DashboardMemoriesMemoryIdDeleteRoute
  DashboardMemoriesMemoryIdEditRoute: typeof DashboardMemoriesMemoryIdEditRoute
}

const DashboardMemoriesRouteChildren: DashboardMemoriesRouteChildren = {
  DashboardMemoriesCreateRoute: DashboardMemoriesCreateRoute,
  DashboardMemoriesDeleteSelectedRoute: DashboardMemoriesDeleteSelectedRoute,
  DashboardMemoriesExportRoute: DashboardMemoriesExportRoute,
  DashboardMemoriesMemoryIdDeleteRoute: DashboardMemoriesMemoryIdDeleteRoute,
  DashboardMemoriesMemoryIdEditRoute: DashboardMemoriesMemoryIdEditRoute,
}

const DashboardMemoriesRouteWithChildren =
  DashboardMemoriesRoute._addFileChildren(DashboardMemoriesRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardDevicesRoute: typeof DashboardDevicesRouteWithChildren
  DashboardMemoriesRoute: typeof DashboardMemoriesRouteWithChildren
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardDevicesRoute: DashboardDevicesRouteWithChildren,
  DashboardMemoriesRoute: DashboardMemoriesRouteWithChildren,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DownloadRouteChildren {
  DownloadLatestDotjsonRoute: typeof DownloadLatestDotjsonRoute
  DownloadTabDotdmgRoute: typeof DownloadTabDotdmgRoute
}

const DownloadRouteChildren: DownloadRouteChildren = {
  DownloadLatestDotjsonRoute: DownloadLatestDotjsonRoute,
  DownloadTabDotdmgRoute: DownloadTabDotdmgRoute,
}

const DownloadRouteWithChildren = DownloadRoute._addFileChildren(
  DownloadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BrandRoute: BrandRoute,
  ComponentsRoute: ComponentsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DownloadRoute: DownloadRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  BillingCheckoutRoute: BillingCheckoutRoute,
  BillingErrorRoute: BillingErrorRoute,
  BillingPortalRoute: BillingPortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
